### ISSUE TITLE
Have some stricter parsing of the dolos.toml config

### ISSUE THREAD

**Issue by mpizenberg** [txpipe/dolos#337]
Currently the parsing of the config file `dolos.toml` is rather permissive and doesn’t prevent or warn in the case of unknown fields, or rather misplaced fields. It got me into trouble because I had manually written:
```toml
[serve]
listen_path = "dolos.socket"
magic = 764824073
```
Instead of `[serve.ouroboros]` for the section title. This lead to an unrelated error message about the database when running `dolos serve`.

It would be very nice if those kind of mistakes where caught at parsing time.
